### ISSUE TITLE
Bot should be able to chat in the lobby chat to indicate game status

### ISSUE THREAD

**Issue by Philaeux** [Philaeux/dazzar#55]
* This requires to implement the chat feature of the library [dota2](https://github.com/ValvePython/dota2/issues/12)
* Afterward, we can use it

**Comment by UncleVasya** [comment]
Hi. I've implemented basic chat features in my fork: https://github.com/UncleVasya/dota2/tree/%231_basic_chat_support

It can join chat. receive and send messages.

I am not making PR yet, cause things like flipping the coin and sharing profiles aren't done. But maybe there's enough for you to continue this ticket :)

----------------

Here's a script that will create a lobby, join lobby chat and respond friendly to any messages:

```
        client = SteamClient()
        dota = Dota2Client(client)
        dota.verbose_debug = True

        @client.on('logged_on')
        def start_dota():
            dota.launch()

        @dota.on('ready')
        def dota_started():
            # if lobby is hung up from previous session, leave it
            dota.leave_practice_lobby()

            dota.create_practice_lobby()

        @dota.on(dota2.features.Lobby.EVENT_LOBBY_NEW)
        def lobby_new(lobby):
            dota.join_lobby_chat(lobby.lobby_id)

        @dota.on(dota2.features.Chat.EVENT_CHAT_JOINED)
        def chat_joined(channel):
            print 'Joined chat!'
            print channel

        @dota.on(dota2.features.Chat.EVENT_CHAT_MESSAGE)
        def chat_message(channel, sender, text, msg_obj):
            dota.send_lobby_message(dota.lobby.lobby_id, 'Fuck off, %s!' % sender)

        client.login(login, password)
        client.run_forever()
```

**Comment by Philaeux** [comment]
Nice work, I will add it to Dazzar as soon as you PR is merged in the master repository.
I also started a branch for chat but never finished it, if you want a peak on it : https://github.com/Philaeux/dota2/tree/chat
